version: '3.8'
services:
  management:
    image: netbirdio/management:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET=525c6eacf89a639731b25c49c81dc60e76ee961f4db791c52c9ab01d1a85f3bf
    ports:
      - "33071:33071"
    volumes:
      - management_data:/var/lib/netbird
      - ./management.json:/etc/netbird/management.json:ro

  signal:
    image: netbirdio/signal:latest
    restart: unless-stopped
    ports:
      - "10000:10000/tcp"
      - "10000:10000/udp"

  dashboard:
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    environment:
      - NETBIRD_MGMT_API_ENDPOINT=http://2.59.80.62:33071
      - NEXT_PUBLIC_MANAGEMENT_API_URL=http://2.59.80.62:33071
      - NEXT_PUBLIC_SIGNAL_API_URL=ws://2.59.80.62:10000
      - AUTH_AUTHORITY=http://2.59.80.62:33071
      - AUTH0_DOMAIN=http://2.59.80.62:33071
      - AUTH0_CLIENT_ID=netbird
      - AUTH0_CLIENT_SECRET=secret
      - AUTH0_AUDIENCE=netbird-api
      - AUTH_CLIENT_ID=netbird
    ports:
      - "3000:3000"
    depends_on:
      - management

volumes:
  management_data:
  